### ISSUE TITLE
falcon-linux-install.sh failing since PR #96

### ISSUE THREAD

**Issue by Sean89us** [CrowdStrike/falcon-scripts#108]
My team has noticed that since #96, the falcon install script fails with this error message:
```
bash: command substitution: line 649: syntax error: unexpected end of file
```

I have attempted to figure out what exactly the problem is here but I see no obvious syntax errors or missing closing brackets, etc. 
If we specify this script at commit [9dfc87b](https://github.com/CrowdStrike/falcon-scripts/commit/9dfc87be49072b0e2c087bb77dd966f094c3c7c5) it works as intended.

This is how we are calling the script in our bootstrapping process:
```
# Install Crowdstrike Falcon
export FALCON_CLIENT_ID="client_id_goes_here"
export FALCON_CLIENT_SECRET="client_secret_goes_here"
export FALCON_CLOUD="us-gov-1"
curl -L https://raw.githubusercontent.com/crowdstrike/falcon-scripts/main/bash/install/falcon-linux-install.sh | bash
```

**Comment by carlosmmatos** [comment]
Understood, will take a look. Thank you for bringing it up.

**Comment by falcon-pioupiou** [comment]
hello @Sean89us, 

Could you tell us on which OS and version you are having this error please ?

I suspect the die command in $() for one of new flags supported.
I'm not able to reproduce this issue on Ubuntu and Centos.

if possible : 
Could run the script with `| bash -x` : 
```
# Install Crowdstrike Falcon
export FALCON_CLIENT_ID="client_id_goes_here"
export FALCON_CLIENT_SECRET="client_secret_goes_here"
export FALCON_CLOUD="us-gov-1"
curl -L https://raw.githubusercontent.com/crowdstrike/falcon-scripts/main/bash/install/falcon-linux-install.sh | bash -x
```

and let us know where you are having the issue please ?
you can copy/paste the last 10-15 lines here (take care to REDACT ANY important info like : CID / token / Credential / hostname / tags / Proxy .... ) - the goal is to look where it's failing in your case.

thanks a lot

**Comment by carlosmmatos** [comment]
@falcon-pioupiou It's reproducible on RHEL/CentOS7:
```
++ cs_target_cid='{
 "meta": {
  "query_time": 0.000177765,
  "powered_by": "binserv",
  "trace_id": "4e6f3030-9293-4241-9763-6db8ba5c71fc"
 },
 "resources": [
  "<CID>"
 ],
 "errors": []
}'
++ '[' -z '{
 "meta": {
  "query_time": 0.000177765,
  "powered_by": "binserv",
  "trace_id": "4e6f3030-9293-4241-9763-6db8ba5c71fc"
 },
 "resources": [
  "<CID>"
 ],
 "errors": []
}' ']'
++ echo '{
 "meta": {
  "query_time": 0.000177765,
  "powered_by": "binserv",
  "trace_id": "4e6f3030-9293-4241-9763-6db8ba5c71fc"
 },
 "resources": [
  "<CID>"
 ],
 "errors": []
}'
++ tr -d '\n" '
++ awk '-F[][]' '{print $2}'
+ cs_falcon_cid=<CID>
bash: command substitution: line 649: syntax error: unexpected end of file
```

**Comment by carlosmmatos** [comment]
Also effects Amazon Linux 2... so probably those systems that are fedora based off RHEL 7

**Comment by carlosmmatos** [comment]
PR #113 should fix this and keep the same functionality

**Comment by Sean89us** [comment]
Hey guys, this issue was on Amazon Linux 2 - which you guys already figured out. Thanks!!
