### ISSUE TITLE
How to deploy to Linux

### ISSUE THREAD

**Issue by watharta** [CrowdStrike/falcon-scripts#112]
Hey y'all, I'm trying to set up the auto installer for Crowdstrike in my Linux environment but I'm running into some issues:

- Am I supposed to use the curl command in the readme.md or is it best practice to fork the repo and use a curl command to my repo? 
- Where am I supposed to put my environment variables? I tried putting them in the repository secrets but still got the same error. 
- Do I need a yaml file in order for the environment variables and script to work as expected?

**Comment by falcon-pioupiou** [comment]
Hello @watharta 

> Am I supposed to use the curl command in the readme.md or is it best practice to fork the repo and use a curl command to my repo?

First you need, to get API Credentials, go to Support > Api client and keys
Create API Client and keys with this scope : Sensor Download (read)

Yes you could setup variable name and run the curl command : 
```
# Install Crowdstrike Falcon
export FALCON_CLIENT_ID="client_id_goes_here"
export FALCON_CLIENT_SECRET="client_secret_goes_here"
curl -L https://raw.githubusercontent.com/crowdstrike/falcon-scripts/main/bash/install/falcon-linux-install.sh | bash
```

if you need `sudo` you can run with this command : 
```
export FALCON_CLIENT_ID="client_id_goes_here"
export FALCON_CLIENT_SECRET="client_secret_goes_here"
curl -L https://raw.githubusercontent.com/CrowdStrike/falcon-scripts/main/bash/install/falcon-linux-install.sh | \
     sudo \
     FALCON_CLIENT_ID=$FALCON_CLIENT_ID \
     FALCON_CLIENT_SECRET=$FALCON_CLIENT_SECRET \
     bash
```

you can fork or use the script directly from github.

> Where am I supposed to put my environment variables? I tried putting them in the repository secrets but still got the same error.

depending how you are deploying and with the tool you are deploying, variables (`FALCON_CLIENT_ID` and `FALCON_CLIENT_SECRET`) must be treated as sensitive info, so you can get them from a vault. But all depends how you are running the install script.

> Do I need a yaml file in order for the environment variables and script to work as expected?

no there is no yaml file, you can pass values to the script as environment variable or configure them in parameters.

**Comment by watharta** [comment]
Legend! Thank you so much, that worked :)
