### ISSUE TITLE
Create versioned releases

### ISSUE THREAD

**Issue by falcon-pioupiou** [CrowdStrike/falcon-scripts#114]
in addition to #110 it would be useful to add versioning and releases

Benefits:
- customers could use a specific version in their production environment without having the risk to have different behaviours over time (as the script continue to evolve).
- it will allow us to make version with breaking changes

**Comment by ffalor** [comment]
Agreed, this is something that is required for things like #92

**Comment by ffalor** [comment]
tagged current main at v1.0.0 & updated readme to curl tag version #121

**Comment by falcon-pioupiou** [comment]
Can we have scripts available directly instead of a zip so we can curl them directly from the release section ?

**Comment by carlosmmatos** [comment]
Not sure I'm following. Currently, you can curl a script using a tagged release.. Is that not what you need?

**Comment by carlosmmatos** [comment]
We do however need to come up with a good release cadence

**Comment by ffalor** [comment]
As carlos pointed out it's possible to download a versioned file currently using branch/sha/tag

However, It's possible to upload & automate the upload using github actions. I'd be fine with this capability.
