### ISSUE TITLE
For Unix (Linux) script allow the FALCON_CLIENT_ID and FALCON_CLIENT_SECRET as parameters

### ISSUE THREAD

**Issue by cecconae** [CrowdStrike/falcon-scripts#138]
For Unix (Linux) script allow the FALCON_CLIENT_ID and FALCON_CLIENT_SECRET as parameters to the script.
This way it is possible to automate the execution without another script to define 
FALCON_CLIENT_ID and FALCON_CLIENT_SECRET as env vars.

**Comment by carlosmmatos** [comment]
@cecconae Thanks for opening an issue. We'll look into adding this, as I think we've talked about it in the past.

**Comment by carlosmmatos** [comment]
For reference, if you would like to pass in FALCON_CLIENT_ID|SECRET from another script, you can do so like:
```shell
FALCON_CLIENT_ID=test FALCON_CLIENT_SECRET=test bash falcon-linux-install.sh
```

**Comment by carlosmmatos** [comment]
Closing as there is no current plans to implement parameters to Linux scripts. Alternative solution has been provided of how to pass in script vars via cli or script.
