### ISSUE TITLE
Cloud_Sensor Installation issue

### ISSUE THREAD

**Issue by chandraloki** [CrowdStrike/falcon-scripts#140]
We are facing an installation issue with falcon and the log suggests the failure at .GetPolicy: Failed to match policy name 'platform_default'. We are using the cloudstrike base address(falcon cloud): https://api.us-2.crowdstrike.com which used to work for us till Feb 20th.   Policy name is basically assigned sensor version but I dont know why its failing. Any suggestions.

**Comment by carlosmmatos** [comment]
@chandraloki there was an issue internally that has been resolved. Can you please try it again?

**Comment by chandraloki** [comment]
Sure @carlosmmatos, just started the deployment again. Will let you know the result.

**Comment by chandraloki** [comment]
Thank you @carlosmmatos, the issue is resolved.
