### ISSUE TITLE
Add the parameter FalconCID on the PowerShell script

### ISSUE THREAD

**Issue by cecconae** [CrowdStrike/falcon-scripts#141]
The retrieved CID is wrong and it is better to place it on the command line the same way as 
FalconClientId and FalconClientSecret, but for that a new parameter need to be added on the script.
I am suggesting FalconCID.    The linux script has this option already.

**Comment by carlosmmatos** [comment]
@cecconae thanks for opening an issue. Are you saying that the powershell install script is retrieving the incorrect CID based on the API key provided? I'm definitely not opposed to adding an additional parameter to support passing in your CID, just trying to understand the current issue as I haven't seen this behavior before.
