### ISSUE TITLE
Change "Node Kernel Mode DaemonSet" in README.md

### ISSUE THREAD

**Issue by kuhnskc** [CrowdStrike/falcon-scripts#202]
Somebody brought this up to me and I figured it was worth sharing. The mention of "Node Kernel Mode DaemonSet" is a little confusing. Since our DaemonSet can be set to run in BPF or Kernel mode, this made it sound like there were separate DaemonSet images for kernel and BPF.

Probably a more clear way to mention it's one Node DaemonSet that can be set to run in kernel or BPF mode.

"Use this bash script to pull the latest Falcon Container sensor, Node Kernel Mode DaemonSet sensor...."

**Comment by carlosmmatos** [comment]
Makes sense to me. @redhatrises what do you think?

**Comment by redhatrises** [comment]
Yeah totally does.... especially as that part was written before eBPF was officially supported in the container image.
