### ISSUE TITLE
Falcon Docker Script Failing with TTY Error

### ISSUE THREAD

**Issue by ctw195** [CrowdStrike/falcon-scripts#203]
Attempting to run the https://github.com/CrowdStrike/falcon-scripts/releases/latest/download/falcon-container-sensor-pull.sh script and receiving the following error message:

"Using the following settings:
Falcon Region: [api.us-2.crowdstrike.com](https://api.us-2.crowdstrike.com/)
Falcon Registry: [registry.crowdstrike.com](https://registry.crowdstrike.com/)
Fatal error: ERROR: /usr/local/bin/docker login failed. Error message: Error: Cannot perform an interactive login from a non TTY device"

How do I get this resolved?

https://falcon.us-2.crowdstrike.com/documentation/page/a36e139f/deploy-falcon-container-sensor-for-linux-using-docker-run

**Comment by carlosmmatos** [comment]
Is this being run from CI like GH actions?

**Comment by OlehFedorenkoSecurrency** [comment]
> Is this being run from CI like GH actions?

I have the same error from my local device

**Comment by carlosmmatos** [comment]
@ctw195 Are you still seeing this issue? I have seen this pop up, specifically around trying to pull the `kpagent`. I updated the API scopes needed per #212 where I was seeing this issue when the API scopes were incorrect.

**Comment by ctw195** [comment]
I ended up giving up on it and downloading the sensor image directly.

**Comment by carlosmmatos** [comment]
Got it. If you end up trying it again, like I said, double check your API scopes before running it. Otherwise I'll go ahead and close this issue and you can re-open it or create a new one in the future if you are still seeing issues.
