### ISSUE TITLE
Requesting Support for Alibaba Cloud Linux 3 OS

### ISSUE THREAD

**Issue by ronyrv13** [CrowdStrike/falcon-scripts#204]
Hello Team,
We are kindly requesting the community's support in adding official support for Alibaba Cloud Linux 3 (Aliyun Linux 3)
This support would benefit users who rely on this operating system for their cloud-based workloads and infrastructure.
Alibaba Cloud Linux 3 is built on Anolis OS 8 and compatible with the CentOS 8 and RHEL 8 ecosystems.

Release note link - https://www.alibabacloud.com/help/en/ecs/user-guide/release-notes-for-alibaba-cloud-linux

We are using Falcon Sensor in our organisation ecosystem, but due to lack of Alibaba Cloud Linux 3 compatibility, we are unable to monitor our servers hosted in Alibaba Cloud.

**Comment by redhatrises** [comment]
@ronyrv13 thank you for opening this issue. 

Unfortunately, the community's support is based on the official product support and roadmap. In other words, if there is no official support in the product, the community is unable to provide support as there is no way for us to do so. The best way to request this feature is to get a hold of your CrowdStrike sales team or TAM or by [creating a request in the ideas portal in the crowdstrike console.](https://us-1.ideas.crowdstrike.com/)

Closing this issue as GitHub isn't the right forum for these requests. Thanks again for raising the issue!
