### ISSUE TITLE
Sensor fails to download - Powershell

### ISSUE THREAD

**Issue by svetecs** [CrowdStrike/falcon-scripts#214]
In Windows, the script auth fine using the client and secret and correctly identifies the policy needed to determine the sensor version.  The script hangs at:
received -1-byte response of content type application/octet-stream

**Comment by carlosmmatos** [comment]
@svetecs thanks for opening an issue. Can you provide some additional information so we can try to help:

1. What version of the script are using?
2. What version of Windows are you running against?
3. Have you tried running with verbosity enabled? https://github.com/CrowdStrike/falcon-scripts/tree/main/powershell/install#troubleshooting

**Comment by svetecs** [comment]
I think this can be closed.  I'm not totally sure why it hung at the stage that it did, but this morning, it seems to be working as expected.  I've just ran the script to download and install as needed and it looks good.
