### ISSUE TITLE
gpg key expired for Linux installations

### ISSUE THREAD

**Issue by yuvalbtretel** [CrowdStrike/falcon-scripts#263]
When trying to import the key using rpm --import I get the following error message:

```
warning: Certificate 4727BBD5519B177F:
  The certificate is expired: The primary key is not live
  Subkey 4727BBD5519B177F is expired: The primary key is not live
  Certificate does not have any usable signing keys
```

**Comment by carlosmmatos** [comment]
@yuvalbtretel - What OS/sensor version are you seeing this? We're not seeing any issues with this and we run against most supported distros every night.

**Comment by yuvalbtretel** [comment]
@carlosmmatos - I imported the key from the script and then ran 
`rpm -K falcon-sensor-7.04.0-15907.el9.x86_64.rpm` 
I am running Fedora 39.
Running `rpm -qpi falcon-sensor-7.04.0-15907.el9.x86_64.rpm` I get 
`Signature   : RSA/SHA512, Sun 08 Oct 2023 02:11:41, Key ID 5e200ce1798bc818` which is a different key than what you provide in your script.

When I reached out to Crowdstrike support they sent me to the download page where a different key (Falcon Linux Sensor RPM signing GPG key 2023.gpg) which I then imported and that resolved the issue. Looks like you should just update the key provided in the script to be the one the official download page provides.

**Comment by carlosmmatos** [comment]
Yup - you're correct, the gpg key we have is not the latest. Will get this updated.

**Comment by carlosmmatos** [comment]
Yeah the install on SLES 15 was complaining about the key but it was still installing the rpm which is why we weren't seeing failures in the CI. The new key should be in today. I'll drop a new release for it.
