### ISSUE TITLE
crowdstrike falcon-sensor rhel 9.4 kernel panic

### ISSUE THREAD

**Issue by jrudley** [CrowdStrike/falcon-scripts#291]
Any update when falcon-sensor will be supported on rhel 9.4? it causes a kernel panic at boot. 
  12.107992] BUG: unable to handle page fault for address: ff33abb0870ced88
[   12.109267] #PF: supervisor write access in kernel mode
[   12.110220] #PF: error_code(0x0002) - not-present page
[   12.111149] PGD 312201067 P4D 312202067 PUD 0 
[   12.111993] Oops: 0002 [#1] PREEMPT SMP NOPTI
[   12.112839] CPU: 1 PID: 933 Comm: falcon-sensor-b Not tainted 5.14.0-427.16.1.el9_4.x86_64 #1

works great on rhel 9.3.

**Comment by redhatrises** [comment]
Hello,

Thanks for opening this issue. This repository doesn't deal with sensor support, roadmap, or when distro/versions will be supported. Please open a CrowdStrike support ticket, talk to your security ops personnel, or CS account team for this information.
