### ISSUE TITLE
Just publish the container image tags in the web UI! Who decided running a script was the way to go??

### ISSUE THREAD

**Issue by mhemken-vts** [CrowdStrike/falcon-scripts#292]
This is a horrendous user experience:
https://github.com/CrowdStrike/falcon-scripts/tree/main/bash/containers/falcon-container-sensor-pull

If I'm logged in to the web UI I should have access to the images. CS knows who I am if I am logged in. CS knows what are the latest published images. **Just figure it out for me and let me copy paste the image tag!**

I have many other things to worry about. I am busy. Don't make me spend extra time dealing with the uninteresting minutia of CrowdStrike configuration.

**Comment by redhatrises** [comment]
Hello,

Thank you for opening this issue. While I completely agree with you that a full registry experience that can be easily accessed via the UI would provide the best user experience, this repository isn't the place to address those asks, needs, or frustrations. Please open a CS support ticket, create/add to an existing ideas via https://us-1.ideas.crowdstrike.com/, and/or talk to your CS representative would probably be the best path forward. Thanks!
