### ISSUE TITLE
Region flag not returning expected (us-1,us-2, eu-1)

### ISSUE THREAD

**Issue by jmckenzie-cs** [CrowdStrike/falcon-scripts#300]
% export FALCON_CLOUD_ENV=$( ./falcon-container-sensor-pull.sh -t falcon-imageanalyzer --region )
% echo $FALCON_CLOUD_ENV
Using the following settings:
Falcon Region:   api.us-2.crowdstrike.com
Falcon Registry: registry.crowdstrike.com
1.0.9: Pulling from falcon-imageanalyzer/us-2/release/falcon-imageanalyzer
Digest: sha256:e84a675c5092bf79acdd0055d892d925393e94a2a7f2efe7aa41391ffd7aed9a
Status: Image is up to date for registry.crowdstrike.com/falcon-imageanalyzer/us-2/release/falcon-imageanalyzer:1.0.9
registry.crowdstrike.com/falcon-imageanalyzer/us-2/release/falcon-imageanalyzer:1.0.9

**Comment by carlosmmatos** [comment]
@jmckenzie-cs - The `-r, --region` flag is intended for setting the region value rather than retrieving it. This flag allows you to specify the region when pulling the image, but it does not return the region value.

**Comment by carlosmmatos** [comment]
If you would like to request additional functionality in the given script, please open up a new issue requesting such. Otherwise, I'm going to close this as there is no action necessary since it's just using the flag incorrectly.
