### ISSUE TITLE
Update policy Name

### ISSUE THREAD

**Issue by clesieug** [CrowdStrike/falcon-scripts#322]
Hello

in powershell/install/falcon_windows_install.ps1
at line 485
$filter = "platform_name:'Windows'+name.raw:'$($SensorUpdatePolicyName.ToLower())'" 

Policy name is case sensitive. Do not convert to Lower.
Change to 
$filter = "platform_name:'Windows'+name.raw:'$($SensorUpdatePolicyName)'" 

Thx

**Comment by carlosmmatos** [comment]
@clesieug thanks for opening this up, somehow this was a regression as we already fixed this in #277 and must have brought it back from the dead 🧟 ... we'll get this fixed in this next version.
