### ISSUE TITLE
Please provide SHA256 checksums and/or PGP signatures with your releases!

### ISSUE THREAD

**Issue by michaelowenfinoa** [CrowdStrike/falcon-scripts#333]
Your scripts look lovely but unfortunately I cannot use them because I cannot verify their integrity or authenticity.

Could you please include SHA256 checksums and/or PGP signatures with your releases? This is a pretty standard practice in security-conscious domains and I am quite surprised neither are available in your releases.

**Comment by carlosmmatos** [comment]
@michaelowenfinoa thanks for opening up the issue. We will look into providing a SHA256 checksums file along with our release artifacts. We'll also backport that for the past releases up to a certain point.

**Comment by carlosmmatos** [comment]
@michaelowenfinoa - I've added a sha256sums.txt file to the last 10 releases as well as a #341 PR that automates it for future releases
