### ISSUE TITLE
Script does not appear to work on Linux Ubuntu 24.04

### ISSUE THREAD

**Issue by MattWeatherford** [CrowdStrike/falcon-scripts#335]
```
root@hgis:~# ./falcon-crowdstrike-agent-install 
Check if Falcon Sensor is running ... [ Not present ]
Falcon Sensor Install  ... Fatal error: No sensor found for with OS Name: Ubuntu
 
root@hgis:~# uname -a
Linux hgis 6.8.0-38-generic #38-Ubuntu SMP PREEMPT_DYNAMIC Fri Jun  7 15:25:01 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
root@hgis:~# more /etc/issue
Ubuntu 24.04 LTS \n \l

 
```

**Comment by redhatrises** [comment]
@MattWeatherford this is because 24.04 is currently unsupported. See https://falcon.crowdstrike.com/documentation/page/edd7717e/falcon-sensor-for-linux-system-requirements

**Comment by rjchwcc** [comment]
Obviously the statement from a couple of years ago that ["we strive for day of support for major OS refreshes"](https://www.reddit.com/r/crowdstrike/comments/qgzrpo/comment/hi9hgik/) hot air then.  24.04 was released three MONTHS ago.

Any news on when it WILL be supported?

**Comment by carlosmmatos** [comment]
@rjchwcc | @MattWeatherford - Believe me, we understand the frustration and apologize for the inconvenience. Unfortunately, our team does not control the project timelines or have influence over them. In fact we face the same limitations from the API side, as we cannot query for information that is not yet available.

Unofficially, we might have a temporary workaround that could help. It may be possible to run the latest Ubuntu sensor in user-mode (bpf) on 24.04, although this is not officially supported. While it's not a perfect solution, it might offer some level of protection until the distribution receives official support.

**Comment by dgisec** [comment]
The early version for ubuntu 24.04 is released: https://supportportal.crowdstrike.com/s/article/Release-Notes-Sensor-Early-Adopter-Program-for-Falcon-Sensor-for-Linux-Version-7-19-17219

it works for upgraded ubuntu. I can see the host on Falcon
It does not work from a fresh install of ubuntu 24.04

Check if Falcon Sensor is running ... [ Not present ]
Falcon Sensor Install  ... 
Fatal error: No sensor found for OS: Ubuntu, Version: 24. Either the OS or the OS version is not 
yet supported.

**Comment by carlosmmatos** [comment]
@dgisec That is because early adopter has nothing to do with the sensor being available to download. If you read the alert it says:

> To opt in, enable Early adopter sensor builds. With this setting enabled, you can specify the sensor update policy to auto-update hosts in your test environment with the latest early adopter sensor version, or select and lock to a specific Early Adopter build.

Which means this only works with sensor update policies to update an existing sensor version up to the early adopter version.

The easiest way to know is to check the sensor downloads page - you will see that this version is not there yet. Once it is, then we will be able to get it from the API.

**Comment by dgisec** [comment]
It works now !

**Comment by carlosmmatos** [comment]
@dgisec - thanks for confirming! Glad this is finally available for you all to use!
