### ISSUE TITLE
Pulling falcon-sensor using the -v flag doesn't accept the values returned by --list-tags

### ISSUE THREAD

**Issue by penicaudm** [CrowdStrike/falcon-scripts#340]
When running the [falcon bash pull script](https://github.com/CrowdStrike/falcon-scripts/blob/main/bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh), the script requires [major.minor] version format for the -v flag. 

This will work:

```bash
sudo ./falcon-container-sensor-pull.sh -u $FALCON_CLIENT_ID -s $FALCON_CLIENT_SECRET -t falcon-sensor -v 7.18 -c myregistry
```

But this doesn't:
```bash
sudo ./falcon-container-sensor-pull.sh -u $FALCON_CLIENT_ID -s $FALCON_CLIENT_SECRET -t falcon-sensor -v 7.18.0-17106-1.falcon-linux.Release.US-1
```

However, I'd like to use it with the following style of script:
```bash

VERSIONS=$(./falcon-container-sensor-pull.sh -u $FALCON_CLIENT_ID -s $FALCON_CLIENT_SECRET -t $image_name --list-tags | awk -v RS=" " '{print}' | grep "$SENSOR_VERSION" | grep -o "[0-9a-zA-Z_\.\-]*")

# Get the latest and n-1 versions
LATEST_VERSION=$(echo "$VERSIONS" | tail -1)

STABLE_VERSION=$(echo "$VERSIONS" | tail -2 | head -1)
```

This would make sense because the versions are returned like this:

```json
{
  "name": "falcon-sensor",
  "repository": "registry.crowdstrike.com/falcon-sensor/us-1/release/falcon-sensor",
  "tags": [
     "7.17.0-17005-1.falcon-linux.Release.US-1",
     "7.18.0-17106-1.falcon-linux.Release.US-1"
  ]
}
```

Would it make sense for the script to accept the full version of the releases for falcon sensor for the -v parameter? 

I have worked around it with this:
```bash
    local pull_version=$version
    if [ "$image_name" = "falcon-sensor" ]; then
        pull_version=$(echo "$version" | cut -d'.' -f1,2)
    fi
```

However I believe this would be slightly easier for automation to accept the tags of the entire versions. 

Regards,

**Comment by carlosmmatos** [comment]
@penicaudm Thanks for opening this issue up and apologies for the delay. I've fixed the issue to address not being able to pass in the full version in #347 . 

As for getting the latest and n-1, I would use `jq` if you have the ability to use it. It would make your ability to get certain versions easier. For example:

```bash
VERSIONS=$(./falcon-container-sensor-pull.sh -u $FALCON_CLIENT_ID -s $FALCON_CLIENT_SECRET -t $image_name --list-tags)

# Get the latest and n-1 versions
LATEST_VERSION=$(echo "$VERSIONS" | jq '.tags | .[-1]')

STABLE_VERSION=$(echo "$VERSIONS" | jq '.tags | .[-2]')
```
