### ISSUE TITLE
falcon-container-sensor-pull does not grab the latest version

### ISSUE THREAD

**Issue by jmganz** [CrowdStrike/falcon-scripts#348]
A [simple tail](https://github.com/CrowdStrike/falcon-scripts/blob/43b5a7ec27287a6cf594bb50f270a821a1889103/bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh#L679) assumes that the results returned are already ordered.

**Comment by carlosmmatos** [comment]
That's because they should be [ordered](https://github.com/CrowdStrike/falcon-scripts/blob/main/bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh#L276).. is this not working for you?

**Comment by jmganz** [comment]
This is not working for me. When I use the script with parameters:
`--region us-gov-1 --type falcon-imageanalyzer`

I receive the following results (removed the `tail -1`):
> name
> falcon-imageanalyzer
> tags
> 0.42.0
> 1.0.10
> 1.0.11
> 1.0.12
> 1.0.13
> 1.0.3
> 1.0.8
> 1.0.9
> name
> falcon-imageanalyzer
> repository
> [registry.laggar.gcw.crowdstrike.com](http://registry.laggar.gcw.crowdstrike.com/)
> falcon-imageanalyzer
> gov1
> release
> falcon-imageanalyzer
> tags
> 0.42.0
> 1.0.10
> 1.0.11
> 1.0.12
> 1.0.13
> 1.0.3
> 1.0.8
> 1.0.9

So 1.0.9 is selected despite 1.0.13 being available. There are also a lot of other strings which I guess the formatting function ensures will not be the last items? I think using awk/sed may be the wrong approach

**Comment by carlosmmatos** [comment]
Appreciate you posting the issue and example! I will definitely look into this and see if we can clean it up. I assume you are running the latest version of the script correct? Just want to make sure I can emulate this in my end.

**Comment by carlosmmatos** [comment]
So running the latest I'm not seeing that issue:
```shell
$ ./falcon-container-sensor-pull.sh -t falcon-imageanalyzer --list-tags -r us-gov-1 | awk -v RS=" " '{print}' | grep "$SENSOR_VERSION" | grep -o "[0-9a-zA-Z_\.\-]*"
name
falcon-imageanalyzer
repository
registry.laggar.gcw.crowdstrike.com
falcon-imageanalyzer
gov1
release
falcon-imageanalyzer
tags
0.42.0
1.0.3
1.0.8
1.0.9
1.0.10
1.0.11
1.0.12
1.0.13
```

and with `tail -1`:
```shell
$ ./falcon-container-sensor-pull.sh -t falcon-imageanalyzer --list-tags -r us-gov-1 | awk -v RS=" " '{print}' | grep "$SENSOR_VERSION" | grep -o "[0-9a-zA-Z_\.\-]*" | tail -1
1.0.13
```

My guess is you are using an older version of the script that doesn't have the changes for version sorting.

**Comment by jmganz** [comment]
Ah, yes. The latest version sorts the versions properly. Sorry about that.

**Comment by jmganz** [comment]
Ah, yes. The latest version sorts the versions properly. Sorry about that.
