### ISSUE TITLE
Falcon agent Install scripts say the Crowdstrike API key doesnt have sufficent permissions, however the permissions required have been granted

### ISSUE THREAD

**Issue by searles9** [CrowdStrike/falcon-scripts#357]
Crowdstrike has provided scripts which install the Falcon Agent onto Azure Windows and Linux VMs.
Those scripts can be found here:
* Linux: https://github.com/CrowdStrike/falcon-scripts/blob/main/bash/install/falcon-linux-install.sh
* Windows: https://github.com/CrowdStrike/falcon-scripts/blob/main/powershell/install/falcon_windows_install.ps1

Ive attached the version of the scripts we are using (remove the .txt extension). 
[LinuxCS (1).sh.txt](https://github.com/user-attachments/files/16615283/LinuxCS.1.sh.txt)
[WindowsCS (1).ps1.txt](https://github.com/user-attachments/files/16615284/WindowsCS.1.ps1.txt)

We got an error saying that the API key was missing permissions (see initial error).

We then granted the API key the permissions required in the error, however after granting those permissions we get a new error (see second error).

Is this an issue with the script?
Is this an issue with Crowdstrike on the back end?
I did notice that the lastest version of the script has an increase in the "ProvWaitTime", i don't think that would cause this issue.
Please advise us on how we can resolve this urgent issue. 

Initial Error:
```
8/6/2024, 2:01:56 PM - Output: PSComputerName        : localhost
PSSourceJobInstanceId : 8ad03789-154f-4031-9c51-db594bd6370f
Code                  : ComponentStatus/StdErr/succeeded
Level                 : Info
DisplayStatus         : Provisioning succeeded
Message               : Insufficient permission error when calling 
                        https://api.crowdstrike.com/policy/combined/sensor-update/v2?filter=platform
                        _name%3a%27Windows%27%2bname.raw%3a%27cloud+and+ad+production+windows+servers%27). Verify the 
                        following scopes are 
                        included in the API key:
                           'Sensor update policies' with: Read
                        At C:\Packages\Plugins\Microsoft.CPlat.Core.RunCommandWindows\1.1.18\Downloads\script1.ps1:272 
                        char:9
                        +         throw $message
                        +         ~~~~~~~~~~~~~~
                            + CategoryInfo          : OperationStopped: (Insufficient pe...ies' with: Read:String) [], 
                        RuntimeException
                            + FullyQualifiedErrorId : Insufficient permission error when calling 
                        https://api.crowdstrike.com/policy/combined/s 
                           ensor-update/v2?filter=platform_name%3a%27Windows%27%2bname.raw%3a%27cloud+and+ad+production+
                        windows+servers%27).   
                          Verify the following scopes are included in the API key:
                           'Sensor update policies' with: Read

Time                  :
```

Error after granting the api key  'Sensor update policies' Read permissions:
```
PSComputerName        : localhost
PSSourceJobInstanceId : b4bba4c1-2f7a-4e93-9818-ed0fb950f197
Code                  : ComponentStatus/StdErr/succeeded
Level                 : Info
DisplayStatus         : Provisioning succeeded
Message               : Unhandled error occurred. Error: Unable to fetch policy details from the CrowdStrike Falcon API.
                        At C:\Packages\Plugins\Microsoft.CPlat.Core.RunCommandWindows\1.1.18\Downloads\script3.ps1:267 
                        char:9
                        +         throw $message
                        +         ~~~~~~~~~~~~~~
                            + CategoryInfo          : OperationStopped: (Unhandled error...ike Falcon API.:String) [], 
                        RuntimeException
                            + FullyQualifiedErrorId : Unhandled error occurred. Error: Unable to fetch policy details 
                        from the CrowdStrike Fal 
                           con API.
 
```

**Comment by carlosmmatos** [comment]
@searles9  - so the version of the scripts you are providing us are v1.3.3 - Have you had the ability to test this using the latest version v1.5.4?

**Comment by searles9** [comment]
> @searles9 - so the version of the scripts you are providing us are v1.3.3 - Have you had the ability to test this using the latest version v1.5.4?

I have not tested the new version. But the only difference I saw between the two was the "ProvWaitTime". Not sure that would cause that issue. 

Thoughts?

**Comment by carlosmmatos** [comment]
A lot has changed: 
- [falcon-linux-install.sh](https://github.com/CrowdStrike/falcon-scripts/compare/v1.3.3...v1.5.4?diff=unified&w=#diff-f6ba02a636e99cc880f6ebb61b9d848e1ab32c79803e2d403a82b8556eb42a8c)
- [falcon_windows_install.ps1](https://github.com/CrowdStrike/falcon-scripts/compare/v1.3.3...v1.5.4?diff=unified&w=#diff-06cb8a8e771b289ec58bb0bd10e47f37e7dee6af781aa9549d8f54079ee1c437)

If it's not too much, please try the latest and report back if you are still having API issues.

**Comment by searles9** [comment]
> s trying to get you direct links to the diffs but I guess it doesn't allow for that.. In the link above, navigate to Files changed -> look for the 2 scripts to see the deltas

Ill try the new script and report back @carlosmmatos

**Comment by searles9** [comment]
@carlosmmatos 

I tried the new windows script and that fixed the windows issue.

i tried the new Linux script and ran into a few issues:

I get this error:
```
                        [stdout]
                        Check if Falcon Sensor is running ... [ Not present ]
                        Falcon Sensor Install  ... 
                        [stderr]
                        Fatal error: No sensor found for with OS Name: Ubuntu
```

Additionally there is a part in the script that checks for positional parameters and I had to remove that:
```
    if [ -n "$1" ]; then
        print_usage
        exit 1
    fi
```
Any chance you can add a flag to ommit this check? We use a powershell command to run the script in the VM. The command has a parameter flag, which sets values as environment variables, but it also seems to think those are positional parameters. 
```
         $scriptResult = Invoke-AzVMRunCommand -ResourceGroupName $ResourceGroup.ResourceGroupName -VMName $_.Name -CommandId 'RunShellScript' -ScriptPath LinuxCS.sh -Parameter @{
                FALCON_CLIENT_SECRET="${crowdstrikeSecret}";
                FALCON_CLIENT_ID="${crowdstrikeId}";
                FALCON_CID="ommited";
                ALLOW_LEGACY_CURL="true";
            } -Verbose
```

**Comment by carlosmmatos** [comment]
@searles9 glad to hear the windows install is working.. 

As for your problem with bash - that is because the script doesn't support positional arguments, in fact this block:
```shell
    if [ -n "$1" ]; then
        print_usage
        exit 1
    fi
```
is precisely there to tell you that. I have an active PR #358 right now that is going to enhance the docs a little around usage/examples that may help you.. but what you want to do is figure out how you can pass these as inline parameters like this:
```shell
FALCON_CLIENT_SECRET="${crowdstrikeSecret}" FALCON_CLIENT_ID="${crowdstrikeId}" FALCON_CID="ommited" ALLOW_LEGACY_CURL="true" ./LinuxCS.sh
```

I'm not too familiar with powershell invoking, perhaps you can use -ScriptString?

Hopefully that works.. otherwise you might need a wrapper script

**Comment by searles9** [comment]
> @searles9 glad to hear the windows install is working..
> 
> As for your problem with bash - that is because the script doesn't support positional arguments, in fact this block:
> 
> ```shell
>     if [ -n "$1" ]; then
>         print_usage
>         exit 1
>     fi
> ```
> 
> is precisely there to tell you that. I have an active PR #358 right now that is going to enhance the docs a little around usage/examples that may help you.. but what you want to do is figure out how you can pass these as inline parameters like this:
> 
> ```shell
> FALCON_CLIENT_SECRET="${crowdstrikeSecret}" FALCON_CLIENT_ID="${crowdstrikeId}" FALCON_CID="ommited" ALLOW_LEGACY_CURL="true" ./LinuxCS.sh
> ```
> 
> I'm not too familiar with powershell invoking, perhaps you can use -ScriptString?
> 
> Hopefully that works.. otherwise you might need a wrapper script

@carlosmmatos You misunderstand.
When I call ```Invoke-AzVMRunCommand``` and pass ```-Parameter``` it sees those values for whatever reason as both positional parameters and as environment variables. To work around that I removed this block from the script:
```
    if [ -n "$1" ]; then
        print_usage
        exit 1
    fi
```
I am still able to do something like this in the script for example and have it work (the script sees them as environment variables):
```
echo $FALCON_CLIENT_ID
```

The issue seems to be that the script cant find the installer for Ubuntu:
```
# This is my script output:
                        Check if Falcon Sensor is running ... [ Not present ]
                        Falcon Sensor Install  ... 
                        [stderr]
                        Fatal error: No sensor found for with OS Name: Ubuntu
```

**Comment by redhatrises** [comment]
@searles9 what Ubuntu version are you attempting to install to?

**Comment by searles9** [comment]
> @searles9 what Ubuntu version are you attempting to install to?

@carlosmmatos It's "Linux (ubuntu 24.04)". However may not be specific to just that OS.

**Comment by redhatrises** [comment]
> > @searles9 what Ubuntu version are you attempting to install to?
> 
> @carlosmmatos It's "Linux (ubuntu 24.04)". However may not be specific to just that OS.

It actually is specific to that OS. The error message that you are receiving is because 24.04 is not yet supported by the sensor. So, the api won't return an installable package until an OS is supported.

**Comment by carlosmmatos** [comment]
@searles9 see #335

**Comment by searles9** [comment]
> @searles9 see #335

@carlosmmatos 
Thanks. That makes sense. I found the FAQ page with the supported OS versions. 
Testing with the new script version and a supported linux OS seems to work from what I can tell so far. 

Could your team implement some sort of change like this?:
```
# Change this original code:
    if [ -n "$1" ]; then
        print_usage
        exit 1
    fi

# To something like this:
if [ -z "$SKIP_POSITIONAL_PARAM_CHECK" ]; then
    if [ -n "$1" ]; then
        print_usage
        exit 1
    fi
fi
```
With this change we would be able to use the script without modification. Currently we have to remove that line (as described in previous comments).

**Comment by carlosmmatos** [comment]
@searles9 I added a change to help out on this area. Basically the only positional argument we'll accept is -h|--help, otherwise we'll continue processing as normal. The assumption here is that people who use this script outside of situations like you have with AzVMRunCommands will continue understanding that it currently operates with environmental variables. In the future, as part of v2 we will introduce the ability to pass both ENV and arguments - similar to how we do with the container-pull script.

**Comment by searles9** [comment]
Great thank you !
@carlosmmatos
