### ISSUE TITLE
Unable to retrieve sensor version from policy 'Windows Sensor Update N-1'. Please check the policy and try again. At C:\Packages\Plugins\Microsoft.Compute.CustomScriptExtension\1.10.17\Downloads\2\falcon_windows_install.ps1:499 char:9 + throw $...

### ISSUE THREAD

**Issue by king-slayer97** [CrowdStrike/falcon-scripts#366]
I have an azure policy that runs the customscript extension on the windows VMs to download and install the falcon sensor. Upon executing the below powershell command on the VM, I get the following error: 
Unable to retrieve sensor version from policy 'Windows Sensor Update N-1'. Please check the policy and try again. At C:\Packages\Plugins\Microsoft.Compute.CustomScriptExtension\1.10.17\Downloads\2\falcon_windows_install.ps1:499 char:9 + throw $...

Command executed:
./falcon_windows_install.ps1 -FalconCid <Falcon Customer ID> -FalconClientId <Falcon Client ID> -FalconClientSecret <Falcon Client Secret> -Tags <Tags to be set seperated by comma> -SensorUpdatePolicyName "Windows Sensor Update N-1"

**Comment by carlosmmatos** [comment]
@king-slayer97 - is this still an issue for you?
