### ISSUE TITLE
Support for contemporary Linux kernels?

### ISSUE THREAD

**Issue by matthiasgoergens** [CrowdStrike/falcon-scripts#371]
The scripts only seem to support ancient kernel (the latest is one year old), and don't support Arch Linux.

Could we fix that, please?

**Comment by carlosmmatos** [comment]
@matthiasgoergens - can you be more specific? I'm assuming you are talking about the bash installation scripts? If so, then correct - CrowdStrike does not currently support Arch Linux so you won't find something for it in our API's. If you would like to see support for Arch, you will have to request it via the official support channels.
