### ISSUE TITLE
falcon-container-sensor-pull.sh --type falcon-kac not evaluating properly

### ISSUE THREAD

**Issue by JamesLochheadCRWD** [CrowdStrike/falcon-scripts#373]
Hi folks,

`--type kalcon-kac` does not seem to be evaluating properly for me and instead is defaulting to the container sensor. Other `--type` uses e.g. `falcon-imageanalyzer` are working fine.

Example:

```
bash falcon-container-sensor-pull.sh --list-tags \
     --client-id REDACTED \
     --client-secret REDACTED \
     --cid REDACTED \
     --region us-1 \
     --type falcon-kac
```

Output:

```
WARNING: The default sensor type of falcon-container is deprecated and will be removed in a future release
{
  "name": "falcon-sensor",
  "repository": "REDACTED",
  "tags": [
     "REDACTED_VERSION.container.x86_64.Release.US-1",
     MORE_VERSIONS_HERE_BUT_REDACTED
  ]
}
```

I have managed to replicate this on MacOS and Ubuntu 22.04.

**Comment by JamesLochheadCRWD** [comment]
> @JamesLochheadCRWD - what is the output of this command:
> 
> ```shell
> bash falcon-container-sensor-pull.sh -h
> ```

Usage: falcon-container-sensor-pull.sh [options]
Version: 1.6.0

Required Flags:
    -u, --client-id <FALCON_CLIENT_ID>             Falcon API OAUTH Client ID
    -s, --client-secret <FALCON_CLIENT_SECRET>     Falcon API OAUTH Client Secret

Optional Flags:
    -f, --cid <FALCON_CID>                         Falcon Customer ID
    -r, --region <FALCON_CLOUD>                    Falcon Cloud Region [us-1|us-2|eu-1|us-gov-1] (Default: us-1)
    -c, --copy <REGISTRY/NAMESPACE>                Registry to copy the image to, e.g., myregistry.com/mynamespace
    -v, --version <SENSOR_VERSION>                 Specify sensor version to retrieve from the registry
    -p, --platform <SENSOR_PLATFORM>               Specify sensor platform to retrieve, e.g., x86_64, aarch64
    -t, --type <SENSOR_TYPE>                       Specify which sensor to download [falcon-container|falcon-sensor|falcon-kac|falcon-snapshot|falcon-imageanalyzer|kpagent|fcs] (Default: falcon-container)

    --runtime <RUNTIME>                            Use a different container runtime [docker, podman, skopeo] (Default: docker)
    --dump-credentials                             Print registry credentials to stdout to copy/paste into container tools
    --get-image-path                               Get the full image path including the registry, repository, and latest tag for the specified SENSOR_TYPE
    --get-pull-token                               Get the pull token of the selected SENSOR_TYPE for Kubernetes
    --get-cid                                      Get the CID assigned to the API Credentials
    --list-tags                                    List all tags available for the selected sensor type and platform, sorted in ascending order
    --allow-legacy-curl                            Allow the script to run with an older version of curl

Internal Flags:
    --internal-build-stage <BUILD_STAGE>           (Internal only) Falcon Build Stage [release|stage] (Default: release)

Help Options:
    -h, --help                                     Display this help message
    
    I always curl the latest one.

**Comment by carlosmmatos** [comment]
hmm that is weird.. I'm not having that issue from my mac or linux systems:
```shell
❯ bash falcon-container-sensor-pull.sh --list-tags --client-id 'REDACTED' --client-secret 'REDACTED' --cid 'REDACTED' --region us-1 --type falcon-kac
{
  "name": "falcon-kac",
  "repository": "<REGISTRY>/falcon-kac/us-1/release/falcon-kac",
  "tags": [
     "VERSION.container.x86_64.Release.US-1",
     ...
  ]
}
```

I always recommend running with debugging on to see what your system is trying to do:
```shell
bash -x falcon-container-sensor-pull.sh --list-tags \
     --client-id REDACTED \
     --client-secret REDACTED \
     --cid REDACTED \
     --region us-1 \
     --type falcon-kac
```

**Comment by JamesLochheadCRWD** [comment]
As per our conversation offline, multi-line commands seem to be breaking parsing of `--type` (but only for the KAC?!) and causing a default to the `falcon-container`.
