### ISSUE TITLE
1605 Error When Attempting to Use Uninstall PS1

### ISSUE THREAD

**Issue by jev217** [CrowdStrike/falcon-scripts#379]
Greetings,

I'm having a issue when I attempt to uninstall CrowdStrike using the [falcon_windows_uninstall.ps1](https://github.com/CrowdStrike/falcon-scripts/blob/main/powershell/install/falcon_windows_uninstall.ps1) across multiple devices of multiple clients dealing with getting a 1605 error.  This error is being shown on across all Windows variants, these devices do confirmed have CrowdStrike installed as we can still see it in the Control Panel and clicking "uninstall" doesn't state "this application isn't on the machine" instead shows the full uninstall GUI.

Error we're getting:
```
PS C:\temp> .\falcon_windows_uninstall.ps1 -FalconClientId CLIENT_ID -FalconClientSecret CLIENT_SECRET
Getting AID before uninstalling
Found AID: AID_Value
Retrieving maintenance token from the CrowdStrike Falcon API.
Retrieved maintenance token: MAINTENANCE_TOKEN
Uninstalling the Falcon Sensor...
Starting uninstaller with parameters: '/uninstall /quiet MAINTENANCE_TOKEN=MAINTENANCE_TOKEN'
Started 'C:\ProgramData\Package Cache\WindowsSensor.exe' (19300)
Uninstaller returned exit code 1605
Uninstaller returned exit code 1605
At C:\temp\falcon_windows_uninstall.ps1:561 char:9
+         throw $Message
+         ~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Uninstaller returned exit cod
   e 1605:String) [], RuntimeException
    + FullyQualifiedErrorId : Uninstaller returned exit code 1605
PS C:\temp>
```

Thank you.

**Comment by redhatrises** [comment]
@jev217 can you try again off from the latest change in the main branch to see if it fixes your issue?

**Comment by jev217** [comment]
Ran with the updated PS1 and received same error, it should be noted I have to put the WIndowsSensor.exe into "C:\ProgramData\Package Cache\" as well.

**Comment by redhatrises** [comment]
Does `WIndowsSensor.exe` or `FalconSensor_Windows.exe` exist under a folder in the `Package Cache` dir? What do the following PS commands show:

```
Get-ChildItem -Path "C:\ProgramData\Package Cache\" -Filter "FalconSensor_Windows.exe" -Recurse
Get-ChildItem -Path "C:\ProgramData\Package Cache\" -Filter "WIndowsSensor.exe" -Recurse
```

**Comment by carlosmmatos** [comment]
@jev217 - Do you get 1605 when you try to manually uninstall via the UI or the CSUninstall Tool?

**Comment by jev217** [comment]
> Does `WIndowsSensor.exe` or `FalconSensor_Windows.exe` exist under a folder in the `Package Cache` dir? What do the following PS commands show:
> 
> ```
> Get-ChildItem -Path "C:\ProgramData\Package Cache\" -Filter "FalconSensor_Windows.exe" -Recurse
> Get-ChildItem -Path "C:\ProgramData\Package Cache\" -Filter "WIndowsSensor.exe" -Recurse
> ```

The WindowsSensor.exe most times is not there in the `Package Cache` dir and I have to put it there manually to clear the error (CrowdStrike support told me to).  Once I put the EXE there then that error clears and I get a 1605 error.



> @jev217 - Do you get 1605 when you try to manually uninstall via the UI or the CSUninstall Tool?

When attempting to uninstall via CSUninstall on the machine I've gone back to work with you guys here it gives no error or any feedback.  If I attempted to uninstall via GUI it works as desired, this just isn't doable as we've a decent amount of devices that are getting this error.

**Comment by carlosmmatos** [comment]
This is strange - I'm just trying to replicate this or understand how to test this out. So just to be clear, does the 1605 error happen on systems where the sensor is missing from the package cache? Have you been able to use this uninstall script on a fresh install system? To me this seems like there is something corrupt in your env, either a partially uninstalled sensor, corrupt package cache or something wrong with the registry. I'm just trying to rule out that if you do a fresh install, and then use the uninstall script, does this error prevail or is it just the systems that you said were missing the cache?

**Comment by jev217** [comment]
If I do a fresh install and use the uninstaller it normally works, this error is on pre-existing clients that we have that we're attempting to remove CrowdStrike off of.  When I run the script most times it will say it can't find the sensor EXE in the package cache.  I'll browse to that cache and I was advised by support to upload the sensor EXE to that directory then I'll attempt to run the uninstaller again which will then error with a 1605.  If this is a corrupt sensor, partially installed sensor, or what have you we need some type of way to remove CrowdStrike off these machines as we can't be expected to do so by hand considering the amount we're potentially looking at.

**Comment by redhatrises** [comment]
> If I do a fresh install and use the uninstaller it normally works, this error is on pre-existing clients that we have that we're attempting to remove CrowdStrike off of. When I run the script most times it will say it can't find the sensor EXE in the package cache. I'll browse to that cache and I was advised by support to upload the sensor EXE to that directory then I'll attempt to run the uninstaller again which will then error with a 1605. If this is a corrupt sensor, partially installed sensor, or what have you we need some type of way to remove CrowdStrike off these machines as we can't be expected to do so by hand considering the amount we're potentially looking at.

@jev217 you might want to try setting the UninstallTool param with the path to the CSUninstallTool

**Comment by jev217** [comment]
I have tried the uninstall parameter.

**Comment by jev217** [comment]
Today I had more devices with the 1605 error when using the script, was able to remote into the servers and uninstall via Control Panel as desired.  This is not going to work for the rest of our devices considering we may have hundreds with this issue.
