### ISSUE TITLE
Deploying falcon sensor in a GKE node using the falcon-linux-install script

### ISSUE THREAD

**Issue by sanjith-porter** [CrowdStrike/falcon-scripts#387]
I tried to install the falcon-sensor in a GKE node , but it didnt work because of OS compatability issues.The GKE node runs on a customized OS which the script doesnt support,are there any other ways to do this?

**Comment by redhatrises** [comment]
For GKE installs, we recommend using https://github.com/CrowdStrike/gcp-vm-manager-os-policy for installing the sensor. For GCOS installs, you need to have FCS, using the daemonset sensor, and install via [helm](https://github.com/CrowdStrike/falcon-helm/tree/main/helm-charts/falcon-sensor) or the [operator](https://github.com/CrowdStrike/falcon-operator).

**Comment by carlosmmatos** [comment]
+1 To you will most likely need to use [falcon-helm](https://github.com/CrowdStrike/falcon-helm/tree/main) or the [falcon-operator](https://github.com/CrowdStrike/falcon-operator) repo's to assist you with your use case of a customized GKE OS.
