### ISSUE TITLE
Linux Installation Script Not working on Ubuntu 24.04 LTS

### ISSUE THREAD

**Issue by c-chieteh** [CrowdStrike/falcon-scripts#388]
Hello, 
I have a bit of an issue installing the Falcon sensor on Ubuntu 24.04 LTS using the Linux installation script.
Whenever I run the script on a fresh Ubuntu 24 installation, I get the following error.
Is there a timeline as to when the script will be updated with this support?
Any help will be highly appreciated
![image](https://github.com/user-attachments/assets/b99520f4-8aa7-406d-bb48-74eb77ba9f64)

**Comment by carlosmmatos** [comment]
@c-chieteh - can you tell us if you are passing in any other parameters via ENV variables?

**Comment by c-chieteh** [comment]
Hello @carlosmmatos 
Yes I am using Env Variables with the command. 
Here's the complete script I am running 
```#/bin/bash

# Setting Env variables
export FALCON_CLIENT_ID=""
export FALCON_CLIENT_SECRET=""
export FALCON_CID=""
export FALCON_CLOUD=""
export FALCON_SENSOR_UPDATE_POLICY_NAME=""
export FALCON_PROVISIONING_TOKEN=""

# Install the Sensor
curl -L https://raw.githubusercontent.com/crowdstrike/falcon-scripts/v1.7.1/bash/install/falcon-linux-install.sh | bash
```

**Comment by carlosmmatos** [comment]
Try running it without this: `FALCON_SENSOR_UPDATE_POLICY_NAME`

Let me know if that works.

**Comment by c-chieteh** [comment]
I tried without the Policy and it works.
I kinda need to install with the policy but I guess that's something I need to figure out on my own.
Thanks a lot for your help @carlosmmatos Much appreciated.

**Comment by carlosmmatos** [comment]
The issue is not so much of using a policy, it's basically because there is only one sensor version currently available for Ubuntu24. So if your policy is using something like N-1 or N-2, that won't exist for that Distro. Eventually in the next few months this won't be an issue as more versions will be released. 

Just something to keep in mind.

**Comment by carlosmmatos** [comment]
Fedora is not currently a supported Distro. You can check the docs to see what Distro's are officially supported. 

That being said, you can try downloading/installing the latest RHEL sensor but of course this is not supported and YMMV.

**Comment by c-chieteh** [comment]
Thanks @carlosmmatos
