### ISSUE TITLE
CSFalconService with Uninstall and Install

### ISSUE THREAD

**Issue by bromandood** [CrowdStrike/falcon-scripts#392]
I have a machine that has the service in a stopped state and not reporting to console (likely broken during remediation efforts of the July incident). I wanted to run an uninstall/re-install but when running the uninstall I get "CSFalconService service not found, already uninstalled" so I then tried to run the install and I then get "CSFalconService running. Falcon sensor is already installed."

Is there a way to uninstall via script even if the service is stopped and the agent is not working?

**Comment by redhatrises** [comment]
In this scenario, it sounds like a _repair_ install with the `WindowsSensor.exe` should be attempted instead of attempting to uninstall and install as a broken installation would most likely prevent proper uninstall and install with the scripts in the first place.

**Comment by bromandood** [comment]
Thanks I gave `Repair-FalconSensor.ps1` a try after this occurred and the script completed successfully but the service was still stopped and the host was not in console.

**Comment by redhatrises** [comment]
OOC have you tried starting the service? Also, have you opened a support ticket with CS which is better equipped to help you?
