### ISSUE TITLE
Is already installed exits with error

### ISSUE THREAD

**Issue by lapkritinis** [CrowdStrike/falcon-scripts#49]
Hello,

I would like to ask to reconsider exit status if sensor is already installed or at least allow ignore it with some argument. I am working with SSM and I don't know simple way to ignore this specific exit status and keep getting reports on other errors.

Output: Falcon Sensor Install ... Preparing... ######################################## ----------ERROR------- Error: Nothing to do package falcon-sensor-6.38.0-13501.el7.x86_64 is already installed failed to run commands: exit status 1
-- | --

**Comment by falcon-pioupiou** [comment]
Hello @lapkritinis 

this is fixed with #95
