### ISSUE TITLE
bash script fail to install properly with the curl call to discover the CID

### ISSUE THREAD

**Issue by kuthz** [CrowdStrike/falcon-scripts#58]
We don't provide the FALCON_CID env variable but with the version https://raw.githubusercontent.com/CrowdStrike/falcon-scripts/042d38af15b699c17c925bc6ff3123f913936d58/bash/install/falcon-linux-install.sh falcon was able to install correctly.

Using the latest version from master (https://github.com/CrowdStrike/falcon-scripts/commit/8023f8fa3ad7e8ed10da48e33f15fc6585ad5c65)
We obtains this error with this version of the script 

```
{code:401,message:accessdenied,invalidbearertoken}" failed checksum validation
ERROR: failed to process the option --cid
```

After some investigation we have a correct access_token but seem to have an error on the call to obtain the CID https://$(cs_cloud)/sensors/queries/installers/ccid/v1

One suggestion, Do you think it's possible to tag a release. This will help to fix a version in the configuration of our image. We will look to use the previous commit hash for now or look to add the CID env variable.

**Comment by falcon-pioupiou** [comment]
Hello, 

this issue was fixed and merged yesterday ( https://github.com/CrowdStrike/falcon-scripts/pull/57 ), 
you can solve it by adding the FALCON_CLOUD variable or just re-download the script like this :

wget -O - https://raw.githubusercontent.com/CrowdStrike/falcon-scripts/main/bash/install/falcon-linux-install.sh | \
     sudo \
     FALCON_CLIENT_ID=<YOUR_FALCON_CLIENT_ID> \
     FALCON_CLIENT_SECRET=<YOUR_FALCON_CLIENT_SECRET> \
     bash

regards

**Comment by kuthz** [comment]
Hi,

thx for the quick fix. I will test it out. 

Do you think it could be possible to add tag/release to fetch a specific script version so this will allow us to don't introduce "breaking change" in our VM build process.

**Comment by kuthz** [comment]
Everything is working properly now as before. I will fetch the specific commit version for now
