### ISSUE TITLE
Illegal characters in path

### ISSUE THREAD

**Issue by r1ckyb0nd** [CrowdStrike/falcon-scripts#61]
Getting the following error, however install still works. 

```
Split-Path : Illegal characters in path.
At line:90 char:9
Split-Path -Parent -Path $MyInvocation.MyCommand.Definition
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    CategoryInfo          : InvalidArgument: (read' and
'sen...  }
    }
}
:String) [Split-Path], ArgumentException
    FullyQualifiedErrorId : ItemExistsArgumentError,Microsoft.PowerShell.Commands.SplitPathCommand
```

**Comment by redhatrises** [comment]
@r1ckyb0nd is there more to the CategoryInfo? Seems cut off.

**Comment by r1ckyb0nd** [comment]
![script-Error](https://user-images.githubusercontent.com/10982727/182646828-bfb680f6-4a6a-4f92-9044-ddd8867be45f.JPG)
This is a snip of the output window

**Comment by redhatrises** [comment]
interesting... can you provide a sanitized version of the cli flags/command that you ran?

**Comment by r1ckyb0nd** [comment]
The only things I changed were I added my API keys.

**Comment by redhatrises** [comment]
What OS/version?

**Comment by r1ckyb0nd** [comment]
OS Name	Microsoft Windows 10 Pro
Version	10.0.19044 Build 19044

**Comment by redhatrises** [comment]
Here's what I ran:

```
PS C:\Users\test\falcon-scripts\powershell\install> .\falcon_windows_install.ps1 -FalconClientId <MYCID> -FalconClientSecret <MYSECRET>
```

Are there weird characters in your path? Seems like that is what the error is complaining about.

**Comment by slowry-lo3** [comment]
I also get the same split-path error when trying to deploy the script via JumpCloud or by running it unsaved with ISE. If I save it, I get the following errors instead when I run it:

`Exception calling "OpenRead" with "1" argument(s): "The remote server returned an error: (403) Forbidden."
At C:\Users\<redacted>\Documents\falcon_windows_install.ps1:174 char:9
+         $Request = $Falcon.OpenRead($Path)
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException
 
New-Object : A constructor was not found. Cannot find an appropriate constructor for type System.IO.StreamReader.
At C:\Users\<redacted>\Documents\falcon_windows_install.ps1:175 char:19
+         $Stream = New-Object System.IO.StreamReader $Request
+                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [New-Object], PSArgumentException
    + FullyQualifiedErrorId : CannotFindAppropriateCtor,Microsoft.PowerShell.Commands.NewObjectCommand
 
You cannot call a method on a null-valued expression.
At C:\Users\<redacted>\Documents\falcon_windows_install.ps1:176 char:9
+         $Output = $Stream.ReadToEnd()
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 
Failed to match policy name 'platform_default'
At C:\Users\<redacted>\Documents\falcon_windows_install.ps1:355 char:9
+         throw $Message
+         ~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Failed to match...atform_default':String) [], RuntimeException
    + FullyQualifiedErrorId : Failed to match policy name 'platform_default'`

**Comment by redhatrises** [comment]
Closing as there has been no further activity on this. Please re-open if needed.
