### ISSUE TITLE
falcon-linux-install.sh leaks credentials

### ISSUE THREAD

**Issue by freedge** [CrowdStrike/falcon-scripts#62]
falcon-linux-install.sh calls curl with the client and secret on the command line. Therefore a user running a ps at the right moment on the same machine can capture the secret.

CrowdStrike itself captures the secret so it can be searched in CrowdStrike events.

To reproduce:
```
export FALCON_CLIENT_ID=dummyclient
export FALCON_CLIENT_SECRET=dummysecret
bash falcon-linux-install.sh 
```

In Falcon console there will be a  ProcessRollup2	event:

```
curl -X POST -s -L https://api.crowdstrike.com/oauth2/token -H Content-Type: application/x-www-form-urlencoded; charset=utf-8 --dump-header /tmp/tmp.ssnTR38c5n -d client_id=dummyclient&client_secret=dummysecret 
```

(https://us-1.ideas.crowdstrike.com/ideas/IDEA-I-4672)

**Comment by isimluk** [comment]
Hello @cdwduobank,

If you have reached these lines above, it means you have set 
```
export  FALCON_SENSOR_UPDATE_POLICY_NAME="xyz"
```

Please make sure that your API credentials have read access to the Falcon Sensor Update Policies. The installer will read the policy and act up on it.

**Comment by cdwduobank** [comment]
> Hello @cdwduobank,
> 
> If you have reached these lines above, it means you have set
> 
> ```
> export  FALCON_SENSOR_UPDATE_POLICY_NAME="xyz"
> ```
> 
> Please make sure that your API credentials have read access to the Falcon Sensor Update Policies. The installer will read the policy and act up on it.

Only env variables I have set are the following but I am still getting that error

FALCON_CLIENT_ID="xxxx"
FALCON_CLIENT_SECRET="yyyy"
