### ISSUE TITLE
Invalid Access Token

### ISSUE THREAD

**Issue by mxheadroom** [CrowdStrike/falcon-scripts#69]
Hello,

When I run the script with the scope set to sensor download (read) I receive an Invalid Access Token error.  I tested the bearer token that was generated separately using a curl get request and it is working fine.

The error matches this portion of the script; which seems to indicate an issue with sensor update policy.  Is there something that needs to set for that?

    if echo "$sensor_update_policy" | grep "authorization failed"; then
        die "Access denied: Please make sure that your Falcon API credentials allow access to sensor update policies (scope Sensor update policies [read])"
    elif echo "$sensor_update_policy" | grep "invalid bearer token"; then
        **die "Invalid Access Token: $cs_falcon_oauth_token"**
    fi

Regards

**Comment by redhatrises** [comment]
Hello,

Per the error message, you need to set `(scope Sensor update policies [read])` on your API client/secret key pair.

**Comment by mxheadroom** [comment]
> Hello,
> 
> Per the error message, you need to set `(scope Sensor update policies [read])` on your API client/secret key pair.

I enabled (scope Sensor update policies [read]) but still same error

Falcon Sensor Install  ... Fatal error: Invalid Access Token: xxxx

I added env variable  FALCON_SENSOR_UPDATE_POLICY_NAME="policyname" and got the above error twice

I tested the token for the error to separately download a package using the following curl call and it was successful

curl -X GET 'https://api.crowdstrike.com/sensors/entities/download-installer/v1?id=4f26d97e63875d3b88648c3d37e4d04edf4e27d418fcd63ec139f1b6da299dd4' -H 'Authorization: Bearer xxxxx' -H 'Content-Type: application/json' --output testfile.rpm

NOTE: I am using the sandbox to test so not sure if that may be the cause of my issue

Regards,

**Comment by redhatrises** [comment]
> > Hello,
> > Per the error message, you need to set `(scope Sensor update policies [read])` on your API client/secret key pair.
> 
> I enabled (scope Sensor update policies [read]) but still same error
> 
> Falcon Sensor Install ... Fatal error: Invalid Access Token: xxxx
> 
> I added env variable FALCON_SENSOR_UPDATE_POLICY_NAME="policyname" and got the above error twice
> 
> I tested the token for the error to separately download a package using the following curl call and it was successful
> 
> curl -X GET 'https://api.crowdstrike.com/sensors/entities/download-installer/v1?id=4f26d97e63875d3b88648c3d37e4d04edf4e27d418fcd63ec139f1b6da299dd4' -H 'Authorization: Bearer xxxxx' -H 'Content-Type: application/json' --output testfile.rpm
> 
> NOTE: I am using the sandbox to test so not sure if that may be the cause of my issue
> 
> Regards,

Hello,

Were you getting the error before you set  `FALCON_SENSOR_UPDATE_POLICY_NAME` or after you set ` FALCON_SENSOR_UPDATE_POLICY_NAME` ?

**Comment by mxheadroom** [comment]
> > > Hello,
> > > Per the error message, you need to set `(scope Sensor update policies [read])` on your API client/secret key pair.
> > 
> > 
> > I enabled (scope Sensor update policies [read]) but still same error
> > Falcon Sensor Install ... Fatal error: Invalid Access Token: xxxx
> > I added env variable FALCON_SENSOR_UPDATE_POLICY_NAME="policyname" and got the above error twice
> > I tested the token for the error to separately download a package using the following curl call and it was successful
> > curl -X GET 'https://api.crowdstrike.com/sensors/entities/download-installer/v1?id=4f26d97e63875d3b88648c3d37e4d04edf4e27d418fcd63ec139f1b6da299dd4' -H 'Authorization: Bearer xxxxx' -H 'Content-Type: application/json' --output testfile.rpm
> > NOTE: I am using the sandbox to test so not sure if that may be the cause of my issue
> > Regards,
> 
> Hello,
> 
> Were you getting the error before you set `FALCON_SENSOR_UPDATE_POLICY_NAME` or after you set ` FALCON_SENSOR_UPDATE_POLICY_NAME` ?

Before.  I also noticed that when I added FALCON_SENSOR_UPDATE_POLICY_NAME I see the error twice instead of once as before adding it

**Comment by isimluk** [comment]
Can you please confirm you have the very latest version of the download script?

I spend several moments to re-create the errors you are seeing, but so far without any luck.

**Comment by mxheadroom** [comment]
> Can you please confirm you have the very latest version of the download script?
> 
> I spend several moments to re-create the errors you are seeing, but so far without any luck.

I used both of the below methods to retrieve and run the script and same error issue

curl -L https://raw.githubusercontent.com/crowdstrike/falcon-scripts/main/bash/install/falcon-linux-install.sh | bash

git clone https://github.com/crowdstrike/falcon-scripts

NOTE: 
I am running the script on a host in AWS so not sure if that may be an issue.  I noticed that the scripts can run using SSM parameters, however I am just setting the variables locally before running the script.

**Comment by carlosmmatos** [comment]
@mxheadroom I'm not sure if you have fixed the issue or not, but if you haven't, to further help diagnose the problem, let's try a few things here:

1. The only reason to get into the `if echo "$sensor_update_policy" | grep "authorization failed"; then` block is if you are passing in a value to the following variable: `FALCON_SENSOR_UPDATE_POLICY_NAME`. For testing purposes, let's ensure your ENV is clear, and that the only variables we are passing are: `FALCON_CLIENT_ID|FALCON_CLIENT_SECRET`
    ```bash
    # view ENV variables and make sure nothing else is set. 
    $ env | grep -i falcon
    ...
    # If you have any results, you can either start a new terminal session for fresh ENV, or you can use the unset ENV command

    # Once we know we have a clean slate, export the ENV vars we need:
    $ export FALCON_CLIENT_ID=<YOUR CLIENT_ID>
    $ export FALCON_CLIENT_SECRET=<YOUR CLIENT SECRET>
    ```
2. Next, we want to run the script with verbosity to better help pin-point issues:
    ```bash
    # If you want to run it via curl:
    $ curl -L https://raw.githubusercontent.com/crowdstrike/falcon-scripts/main/bash/install/falcon-linux-install.sh | bash -x
    
    # If you are running it via the repo:
    $ bash -x ./falcon-linux-install.sh
    ```
Let's see where that gets us.

**Comment by mxheadroom** [comment]
> @mxheadroom I'm not sure if you have fixed the issue or not, but if you haven't, to further help diagnose the problem, let's try a few things here:
> 
>     1. The only reason to get into the `if echo "$sensor_update_policy" | grep "authorization failed"; then` block is if you are passing in a value to the following variable: `FALCON_SENSOR_UPDATE_POLICY_NAME`. For testing purposes, let's ensure your ENV is clear, and that the only variables we are passing are: `FALCON_CLIENT_ID|FALCON_CLIENT_SECRET`
>        ```shell
>        # view ENV variables and make sure nothing else is set. 
>        $ env | grep -i falcon
>        ...
>        # If you have any results, you can use the `unset <ENV>` command
>        
>        # Once we know we have a clean slate, export the ENV vars we need:
>        $ export FALCON_CLIENT_ID=<YOUR CLIENT_ID>
>        $ export FALCON_CLIENT_SECRET=<YOUR CLIENT SECRET>
>        ```
> 
>     2. Next, we want to run the script with verbosity to better help pin-point issues:
>        ```shell
>        # If you want to run it via curl:
>        $ curl -L https://raw.githubusercontent.com/crowdstrike/falcon-scripts/main/bash/install/falcon-linux-install.sh | bash -x
>        
>        # If you are running it via the repo:
>        $ bash -x ./falcon-linux-install.sh
>        ```
> 
> 
> Let's see where that gets us.

I will spin up a new host to use for testing.  I'll let you know the result once completed

**Comment by carlosmmatos** [comment]
@mxheadroom just checking in to see if any of the latest updates have helped with this issue.

**Comment by carlosmmatos** [comment]
Closing since we've not heard back as to whether the issue exists, and we can't reproduce it on our side.
