### ISSUE TITLE
The latest CrowdStrike sensor supports Ubuntu 22.04 but the script doesn't download it.

### ISSUE THREAD

**Issue by alanbchk** [CrowdStrike/falcon-scripts#74]
The latest CrowdStrike sensor (6.46.14306) supports Ubuntu 22.04 but the script doesn't download it.
![image](https://user-images.githubusercontent.com/56105431/193853150-fd8120a0-b176-4da7-a10a-d68aef46f355.png)

The script would only download the older version, thus putting the host in RFM (Reduced Functionality Mode)

**Comment by carlosmmatos** [comment]
I'll take a look

**Comment by carlosmmatos** [comment]
@alanbchk so I ran the script as is on an Ubuntu 22.04 system and it's pulling down falcon-sensor_6.46.0-14306_amd64.deb just fine. 

I would suggest running it with `-x` to look over the variable assignments and curl commands. 

ie `bash -x falcon-linux-install.sh`

**Comment by isimluk** [comment]
I am closing this issue now based on insufficient data; after 14 days of inactivity. Please feel free to re-open when new information emerges.
