### ISSUE TITLE
Cannot locate matching sensor for Amazon Linux 2

### ISSUE THREAD

**Issue by chaosun-abnormalsecurity** [CrowdStrike/falcon-scripts#76]
```
Falcon Sensor Install  ... Fatal error: Unable to locate matching sensor: Amazon Linux, version: 2
```

Looking into the install script, it seems the [os_version](https://github.com/CrowdStrike/falcon-scripts/blob/main/bash/install/falcon-linux-install.sh#L397) and [cs_os_version](https://github.com/CrowdStrike/falcon-scripts/blob/main/bash/install/falcon-linux-install.sh#L451) it got was `"2"`, while the versions queried into [existing_installers](https://github.com/CrowdStrike/falcon-scripts/blob/main/bash/install/falcon-linux-install.sh#L141) are `"2 arm64"`, `"2 amd64"` etc.

**Comment by carlosmmatos** [comment]
@chaosun-abnormalsecurity sorry for the delayed response on this one. Let me know if this is working for you now.

**Comment by chaosun-abnormalsecurity** [comment]
@carlosmmatos Yes it is working now. Thanks!
