### ISSUE TITLE
falcon-linux-isntall script cs_os_name case statement matches Debian to "RHEL/CentOS/Oracle"

### ISSUE THREAD

**Issue by nhempenius** [CrowdStrike/falcon-scripts#79]
The case statement for cs_os_name in the falcon-linux-install.sh script has a typo. 

Debian OS name resolves to "RHEL/CentOS/Oracle" because "Debian" is included in the match on line 421. 

https://github.com/CrowdStrike/falcon-scripts/blob/main/bash/install/falcon-linux-install.sh#L421

Obviously only affects installing with Debian and easy to fix manually but wanted to share.

**Comment by carlosmmatos** [comment]
@nhempenius thanks for the issue! Will definitely look into fixing this next week.
