### ISSUE TITLE
Enhance uninstall / install script with additional features

### ISSUE THREAD

**Issue by ps4signedout** [CrowdStrike/falcon-scripts#92]
usecase: migration from US to EU i.e.
steps:
1. retrieve uninstall token by using API (no powershell SDK integration)
2. retrieve all relevant tags (sensor AND Falcon) from old environment
3. write all into $hostname.csv (configurable)
4. uninstall sensor
6. verify uninstall
7. download sensor and retrieve CID
8. install sensor including sensor-tags as derived from step 2  from CSV file of #3
9. retrieve maintenance token from new environment
10. set Falcon tags derived in step 2 from CSV file of #3
11. verify sensor
12. remove orphaned host from old environment or set FLAG "moved" 

Most probably it will not be one script more like an uninstall.ps1 && install.ps1 approach ;-)

**Comment by ffalor** [comment]
Changes to install/uninstall:

- [ ] Support `ProvToken` in install script
- [ ] Support `MAINTENANCE_TOKEN` in uninstall script 
- [ ] Hide host in console after uninstall (via flag)


Migration Script:

- [ ] Add migration script to support migrating falcon clouds
